[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
utils    = { path = "../utils" }
renet      = "2.0.0"
renet_netcode  = "2.0.0"
tokio      = { version = "1.52", features = ["full"] }
bincode = "2"
legion   = "0.4"
rand = "0.10.1"
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
arrayvec = "0.7.7"
itertools = "0.15"